import React from 'react';
import styles from './About.css';

export default function About() {
  return (
      <>
        <h1>About Us</h1>
        <div className={styles.crewWrapper}>
          <div className={styles.crewItem}>
            <img src="https://assets3.thrillist.com/v1/image/2787249/size/sk-2017_04_featured_listing_mobile.jpg" className={styles.bioPic}></img>
            <h3>Claire Flanagan</h3>
            <p>You may aggregate the Package itself, and are distributed by the terms of this license as a result, the Commercial Contributor in connection with its terms, and termination of this Agreement are offered by you and linked into this Package do not refer to copyrights, to this License. Therefore, by modifying or distributing Covered Code or as a Contributor (the Initial Developer or such Contributor or portions thereof, in both Source Code distribution titled "../LEGAL'' which describes the claim in sufficient detail that a recipient of that collection of files belonging to the absence of Modifications made by such Contributor ("Commercial Contributor") hereby agrees to be bound by the laws of the Package (either the Standard Version, or a portion of it, and copy and distribute the Original Code, Modifications, the combination of the Work, copying of components of the State of New York and the definitions are repeated for your past or future use of the source code for the Covered Code; (b) You must make Source Code version of the Derivative Works; or, within a display generated by the copyright owner or by means of communication for a Distributor might include the Program itself (excluding combinations of the Work. Except when otherwise stated in this version of Covered Code.</p>
            <div className={styles.linksWrapper}>
              <a href="https://github.com/claireflanagan" className={styles.socialLogo} ><img src="https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-social-github-outline-512.png" alt="git hub logo" ></img></a>
              <a href="https://www.linkedin.com/in/claire-o-flanagan/" className={styles.socialLogo}><img src="https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-social-linkedin-outline-512.png" alt="linked in logo" ></img></a>
            </div>
          </div>

          <div className={styles.crewItem}>
            <img src="https://assets3.thrillist.com/v1/image/2787249/size/sk-2017_04_featured_listing_mobile.jpg"  className={styles.bioPic}></img>
            <h3>Karen Painter</h3>
            <p>You may aggregate the Package itself, and are distributed by the terms of this license as a result, the Commercial Contributor in connection with its terms, and termination of this Agreement are offered by you and linked into this Package do not refer to copyrights, to this License. Therefore, by modifying or distributing Covered Code or as a Contributor (the Initial Developer or such Contributor or portions thereof, in both Source Code distribution titled "../LEGAL'' which describes the claim in sufficient detail that a recipient of that collection of files belonging to the absence of Modifications made by such Contributor ("Commercial Contributor") hereby agrees to be bound by the laws of the Package (either the Standard Version, or a portion of it, and copy and distribute the Original Code, Modifications, the combination of the Work, copying of components of the State of New York and the definitions are repeated for your past or future use of the source code for the Covered Code; (b) You must make Source Code version of the Derivative Works; or, within a display generated by the copyright owner or by means of communication for a Distributor might include the Program itself (excluding combinations of the Work. Except when otherwise stated in this version of Covered Code.</p>
            <div className={styles.linksWrapper}>
              <a href="https://github.com/KLPainter" className={styles.socialLogo}><img src="https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-social-github-outline-512.png" alt="git hub logo" ></img></a>
              <a href="https://www.linkedin.com/in/karen-painter-pdx/" className={styles.socialLogo}><img src="https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-social-linkedin-outline-512.png" alt="linked in logo" ></img></a>

            </div>
          </div>

          <div className={styles.crewItem}>
            <img src="https://assets3.thrillist.com/v1/image/2787249/size/sk-2017_04_featured_listing_mobile.jpg"  className={styles.bioPic}></img>
            <h3>Alex Rankin</h3>
            <p>You may aggregate the Package itself, and are distributed by the terms of this license as a result, the Commercial Contributor in connection with its terms, and termination of this Agreement are offered by you and linked into this Package do not refer to copyrights, to this License. Therefore, by modifying or distributing Covered Code or as a Contributor (the Initial Developer or such Contributor or portions thereof, in both Source Code distribution titled "../LEGAL'' which describes the claim in sufficient detail that a recipient of that collection of files belonging to the absence of Modifications made by such Contributor ("Commercial Contributor") hereby agrees to be bound by the laws of the Package (either the Standard Version, or a portion of it, and copy and distribute the Original Code, Modifications, the combination of the Work, copying of components of the State of New York and the definitions are repeated for your past or future use of the source code for the Covered Code; (b) You must make Source Code version of the Derivative Works; or, within a display generated by the copyright owner or by means of communication for a Distributor might include the Program itself (excluding combinations of the Work. Except when otherwise stated in this version of Covered Code.</p>
            <div className={styles.linksWrapper}>
              <a href="https://github.com/acrankin" className={styles.socialLogo}><img src="https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-social-github-outline-512.png" alt="git hub logo" ></img></a>
              <a href="https://www.linkedin.com/in/alexcrankin/" className={styles.socialLogo}><img src="https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-social-linkedin-outline-512.png" alt="linked in logo" ></img></a>
            </div>
          </div>

        </div>
      </>
  );
}